const Colors = {
  // PRIMARY: '#FF9009',
  PRIMARY: '#4bcbd0',
  // PRIMARY: '#5f8cff',
  SECONDARY: '',

  PRIMARY_TEXT: '#000000',
  GREY: '#D4D4D4',

  PRIMARY_BACKGROUND: '#FFFFFF',

  TAB_ICON: '#b0b0b0',
  INPUT_BACKGROUND: '#00000010',
  INPUT_FOCUSED_BACKGROUND: '#4bcbd020',
  // INPUT_FOCUSED_BACKGROUND: '#5f8cff20',
  DROPDOWN_MENU_BACKGROUND: '#EAEAEA',

  ERROR_TEXT: '#FF0000',
  ERROR_INPUT_BACKGROUND: '#FF000010',

  WHITE: '#FFFFFF',
  BLACK: '#000000',
  TRANSPARENT: 'transparent',
};

export {Colors};
