export const AppIcons = {
  apple: require('../assets/icons/apple.png'),
  back: require('../assets/icons/back.png'),
  booking: require('../assets/icons/booking.png'),
  calendar: require('../assets/icons/calendar.png'),
  check: require('../assets/icons/check.png'),
  close_eye: require('../assets/icons/close_eye.png'),
  close: require('../assets/icons/close.png'),
  down_arrow: require('../assets/icons/down_arrow.png'),
  eye: require('../assets/icons/eye.png'),
  facebook: require('../assets/icons/facebook.png'),
  google: require('../assets/icons/google.png'),
  home: require('../assets/icons/home.png'),
  invite: require('../assets/icons/invite.png'),
  language: require('../assets/icons/language.png'),
  lock: require('../assets/icons/lock.png'),
  logout: require('../assets/icons/logout.png'),
  mail: require('../assets/icons/mail.png'),
  map: require('../assets/icons/map.png'),
  message: require('../assets/icons/message.png'),
  moon: require('../assets/icons/moon.png'),
  notification: require('../assets/icons/notification.png'),
  profile: require('../assets/icons/profile.png'),
  security: require('../assets/icons/security.png'),
  user: require('../assets/icons/user.png'),
  wallet: require('../assets/icons/wallet.png'),
};
